
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: r1
              uri: http://localhost:8081
              predicates:
                - Path=/api/customers/**
            - id: r2
              uri: http://localhost:8082
              predicates:
                - Path=/api/products/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"